### ISSUE TITLE
Сломалось

### ISSUE THREAD

**Issue by JokerSSmile** [AnatolyKorablyov/anatolykorablyov.github.io#1]
![img_18022017_003422_0](https://cloud.githubusercontent.com/assets/14825145/23084228/64ce2b6a-f572-11e6-88ca-4bf4f99ea53e.png)

**Comment by AnatolyKorablyov** [comment]
починил

**Comment by JokerSSmile** [comment]
Неправда

**Comment by AnatolyKorablyov** [comment]
а ты проверь
